import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {playerById,playersByPosition} from "../../../lib/michigan/roster";
import {classLabel,formatHeight} from "../../../lib/michigan/format";
import {storiesForPlayer} from "../../../lib/michigan/stories";

type Props={params:Promise<{playerId:string}>};
const statValue=(value:number)=>Number.isInteger(value)?value.toLocaleString():value.toFixed(1);

export async function generateMetadata({params}:Props):Promise<Metadata>{const p=playerById((await params).playerId);if(!p)return{title:"Player not found",openGraph:{images:[]},twitter:{images:[]}};const title=`${p.firstName} ${p.lastName} | Michigan`;const description=`2026 Michigan ${p.position??"player"} profile, past production and preseason outlook.`;const images=p.playerImageUrl?[p.playerImageUrl]:[];return{title,description,openGraph:{title,description,images},twitter:{title,description,images}}}

export default async function PlayerPage({params}:Props){
  const p=playerById((await params).playerId);if(!p)notFound();const room=playersByPosition(p.position??"");const insight=p.insight;const freshman=p.rosterStatus==="FRESHMAN";const focusValue=freshman?(p.stars?"★".repeat(p.stars):"UNRATED"):(p.performanceGrade??"NG");const focusDetail=freshman?(p.compositeRating?`${p.compositeRating.toFixed(4)} composite · ${p.nationalRecruitRank?`No. ${p.nationalRecruitRank} nationally`:"no national rank"}`:"No verified composite rating"):(p.performanceGrade?`${insight?.focus.percentile?.toFixed(1)??"—"}th position percentile`:"No measured 2025 usage; no production grade");
  const stories=storiesForPlayer(p.id);
  return <article className="player-profile-page">
    <header className="player-profile-hero"><div className="wrap player-profile-hero-inner"><div className="player-profile-copy"><span className="kicker">2026 MICHIGAN · {p.position??"ATH"} · {p.rosterStatus??"ROSTER"}</span><h1>{p.firstName}<br/><b>{p.lastName}</b></h1><p>#{p.jersey??"—"} · {formatHeight(p.height)} · {p.weight?`${p.weight} lbs`:"Weight —"} · {classLabel(p.year)}<br/>{[p.homeCity,p.homeState].filter(Boolean).join(", ")||"Hometown —"}</p>{p.playerImageSourceUrl&&<a className="player-photo-source" href={p.playerImageSourceUrl}>PHOTO: {p.playerImageSource} ↗</a>}</div><div className="player-profile-image">{p.playerImageUrl?<img src={p.playerImageUrl} alt={`${p.firstName} ${p.lastName}`}/>:<strong>{p.jersey??"M"}</strong>}</div><div className="profile-focus"><small>{freshman?"PROSPECT PROFILE":"2025 PRODUCTION"}</small><strong className={freshman?"stars-focus":""}>{focusValue}</strong><span>{focusDetail}</span><i>{freshman?"BENCHMARK":"ACTUAL"}</i></div></div></header>
    <div className="wrap player-profile-stack">
      <section className="profile-stat-section"><header className="section-header"><div><span className="kicker navy">PAST SEASONS</span><h2>What he has put on tape.</h2></div><small>ACTUAL · PUBLIC BOX-SCORE STATS</small></header>{insight?.pastSeasons.length?<div className="profile-season-list">{insight.pastSeasons.map(season=><article key={`${season.season}-${season.team}`}><header><b>{season.season}</b><span>{season.team}</span></header><div>{season.stats.map(stat=><span key={stat.label}><small>{stat.label}</small><strong>{statValue(stat.value)}</strong></span>)}</div></article>)}</div>:<div className="profile-empty"><b>No non-zero college box-score statistics yet.</b><p>{freshman?"That is expected for a first-year player. Recruiting evidence remains the honest baseline until college usage arrives.":"Public box scores do not capture every role—especially offensive-line snaps and special-teams assignments. A production grade will appear only after measurable usage exists."}</p></div>}</section>
      <section className="profile-read"><div><span className="kicker navy">2026 OUTLOOK</span><h2>{insight?.expectation??"Turn opportunity into dependable snaps."}</h2><p>{insight?.expectationBasis}</p></div><div className="profile-pro-con"><article><small>STRENGTH SIGNALS</small>{insight?.strengths.length?insight.strengths.map(item=><p key={item}>+ {item}</p>):<p>+ Evaluation begins with the available roster and recruiting evidence.</p>}</article><article><small>GROWTH AREAS</small>{insight?.growthAreas.map(item=><p key={item}>— {item}</p>)}</article></div></section>
      <section className="profile-context"><div><span>POSITION ROOM</span><strong>{room.length}</strong><small>{p.position??"ATH"} PLAYERS</small></div><div><span>RECRUITING</span><strong>{p.prospectGrade??"NR"}</strong><small>{p.stars?`${p.stars}-STAR · ${p.compositeRating?.toFixed(4)??"NO RATING"}`:"NO MATCHED COMPOSITE"}</small></div><div><span>CAREER PATH</span><strong>{p.careerTimeline?.length??0}</strong><small>{p.careerTimeline?.map(entry=>`${entry.season} ${entry.team}`).join(" · ")||"NO EARLIER ROSTER SEASONS"}</small></div></section>
      {stories.length>0&&<section className="player-articles"><header className="section-header"><div><span className="kicker navy">IN THE NOTEBOOK</span><h2>Stories featuring {p.firstName}.</h2></div><Link href="/articles">ALL ARTICLES →</Link></header><div>{stories.map(story=><Link href={`/articles/${story.slug}`} key={story.slug}><span><small>{story.eyebrow} · {story.readMinutes??5} MIN</small><strong>{story.title}</strong><p>{story.deck}</p><b>READ →</b></span></Link>)}</div></section>}
      <nav className="profile-links" aria-label="Continue exploring"><Link href={`/team/positions/${(p.position??"").toLowerCase()}`}>POSITION ROOM →</Link><Link href="/analytics">TEAM ANALYTICS →</Link><Link href="/team">TEAM OUTLOOK →</Link><Link href="/team/roster">FULL ROSTER →</Link></nav>
    </div>
  </article>;
}
