import { currentRoster } from "./roster";
import { currentRecruitingClass } from "./recruiting";

export type StoryTagType = "POSITION"|"UNIT"|"TOPIC";
export type StoryTag = {type:StoryTagType;slug:string;label:string};
export type StoryDataLink = {label:string;href:string;description:string};
export type MichiganStory = { slug:string; eyebrow:string; title:string; deck:string; body:string[]; playerIds?:string[]; published?:string; readMinutes?:number; tags:StoryTag[]; dataLinks:StoryDataLink[]; coverQuestion?:string; coverLabel?:string; coverTheme?:string; sources?:{label:string;url:string}[] };

const positionUnit=(position?:string|null):"OFFENSE"|"DEFENSE"|"SPECIAL TEAMS" => ["QB","RB","WR","TE","OL"].includes(position??"")?"OFFENSE":["K","P","LS"].includes(position??"")?"SPECIAL TEAMS":"DEFENSE";
const tag=(type:StoryTagType,slug:string,label:string):StoryTag=>({type,slug,label});

export function michiganStories(): MichiganStory[] {
  const roster = currentRoster();
  const score = {"S+":7,S:6,A:5,B:4,C:3,D:2,F:1};
  const featured = roster.filter(p=>p.prospectGrade).sort((a,b)=>(score[b.prospectGrade!]??0)-(score[a.prospectGrade!]??0)).slice(0,4);
  const playerStories = featured.map((player):MichiganStory=>({
    slug:`player-${player.id}`, playerIds:[player.id], eyebrow:`${player.position ?? "PLAYER"} NOTEBOOK · 2026`,
    title:`The ${player.firstName} ${player.lastName} question`, readMinutes:4,
    coverQuestion:`How soon can ${player.firstName} change Michigan's plans?`, coverLabel:player.position??"PLAYER", coverTheme:(player.position??"player").toLowerCase(),
    deck:`Where Michigan's ${player.position ?? "roster"} profile meets the opportunity ahead.`,
    tags:[tag("POSITION",(player.position??"player").toLowerCase(),player.position??"Player"),tag("UNIT",positionUnit(player.position).toLowerCase().replace(" ","-"),positionUnit(player.position)),tag("TOPIC","player-development","Player development")],
    dataLinks:[{label:`${player.firstName} ${player.lastName} profile`,href:`/players/${player.id}`,description:"Verified roster identity, recruiting benchmark, past production and preseason role."},{label:"Michigan roster",href:"/team",description:"See where this player fits in the complete 2026 squad."}],
    body:[
      `${player.firstName} ${player.lastName} enters the 2026 preseason wearing No. ${player.jersey ?? "—"} at ${player.position ?? "an unlisted position"}. At ${player.height ? `${Math.floor(player.height/12)}-foot-${player.height%12}` : "an unlisted height"} and ${player.weight ? `${player.weight} pounds` : "an unlisted weight"}, the roster profile sets the frame—not the conclusion.`,
      player.compositeRating ? `The recruiting record supplies a ${player.compositeRating.toFixed(4)} composite and a ${player.prospectGrade} Michigan display grade. That is useful context for pedigree, but it is not a claim about present performance or a promise about the depth chart.` : `No recruiting composite matched the current roster identity, so the profile stays unrated rather than filling the gap with a guess.`,
      `The story to follow is role: how Michigan deploys this skill set, what the weekly workload becomes, and how the production changes against Big Ten competition. Those answers will be added from observed games.`
    ]
  }));
  const recruiting = currentRecruitingClass();
  const researched:MichiganStory[]=[
    {slug:"new-age-era",eyebrow:"TEAM 147 · SEASON PREVIEW",title:"A New Age: why Michigan’s reset could arrive ahead of schedule",deck:"A program bruised by instability now hands a hungry roster to Kyle Whittingham. Utah’s 2025 strengths, Michigan’s unfinished offense and Bryce Underwood’s second-year leap create a credible path to becoming the Big Ten’s surprise team.",published:"August 19, 2026",readMinutes:11,playerIds:["5141741","5079574","5159046","5160962","5141572"],coverQuestion:"Can a proven culture unlock Michigan’s young core?",coverLabel:"THE NEW AGE",coverTheme:"new-era",tags:[tag("POSITION","qb","QB"),tag("UNIT","offense","Offense"),tag("UNIT","defense","Defense"),tag("TOPIC","coaching","Coaching"),tag("TOPIC","season-preview","Season preview"),tag("TOPIC","transfer-portal","Transfer portal")],dataLinks:[{label:"Michigan vs. Utah",href:"/analytics",description:"Compare the verified 2025 efficiency, explosiveness, third-down and finishing metrics behind the coaching transition."},{label:"Team 147 roster",href:"/team",description:"Explore the returning core, incoming transfers and freshmen who will define Whittingham's first Michigan team."},{label:"2026 schedule",href:"/schedule",description:"Follow the 12-game path through Oklahoma, Penn State, Oregon and Ohio State."},{label:"Bryce Underwood profile",href:"/players/5141741",description:"Review the production and usage behind the most important offseason in Michigan's 2026 outlook."}],body:[
      "Michigan’s new age begins with an uncomfortable truth: the change was not planned. The university fired Sherrone Moore for cause after saying its investigation found credible evidence that he had engaged in an inappropriate relationship with a staff member. A broader review of athletic-department culture followed. It would be irresponsible to claim we know where Moore’s mind was every Saturday. It is fair to say the head coach failed the leadership and accountability standard of the job, leaving his players to absorb another rupture at the top of the program.",
      "That distinction matters because this team is not a blank rebuild. Michigan won nine regular-season games in 2025 and remained in the playoff conversation late, yet its offense often looked closer to functional than complete. SOAR’s play-level data places Michigan 18th nationally in overall success rate and shows a 50.9 percent rushing success rate with 6.01 yards per attempt. The Wolverines could stay on schedule and create useful runs. The damage came later: they averaged only 3.40 points per scoring opportunity, 78th nationally. Too many good drives became field goals, failed fourth downs or empty possessions.",
      "Kyle Whittingham arrives with a model for solving exactly that problem. Utah’s 2025 offense was not radically different in its starting premise. Utah called runs on 58.5 percent of designed run-or-dropback plays; Michigan was at 57.1 percent. Both wanted the ground game to organize the afternoon. Utah simply made the structure pay. The Utes ranked 11th in success rate, converted 52.0 percent of third downs, generated an explosive run on 18.6 percent of rushing attempts and scored 4.44 points per opportunity, also 11th nationally.",
      "That is the promise of the hire—not that Michigan will become Utah overnight, but that Whittingham, offensive coordinator Jason Beck and defensive coordinator Jay Hill bring a shared operating language. Michigan does not need a personality transplant. It needs cleaner situational football, better answers when a defense knows a pass is coming and a harder edge when drives cross midfield. Utah’s 2025 numbers are staff context rather than a projection, but they show that this staff has recently built the very bridge Michigan was missing between moving the ball and scoring with it.",
      "The roster construction reinforces the cultural handoff. Michigan’s published preseason roster includes 16 transfers. John Henry Daley brings the loudest résumé after producing 17.5 tackles for loss and 11.5 sacks at Utah. Smith Snowden and Jonah Lea’ea also followed from Utah, while JJ Buchanan adds another familiar voice on offense. Jaime Ffrench gives the receiver room former five-star talent, Brayden Fowler-Nicolosi supplies experienced quarterback depth, and Houston Ka’aha’aina-Torres enters the offensive-line competition after Nebraska. Familiarity does not guarantee production, but it gives Whittingham players who can demonstrate his standards instead of merely repeating them.",
      "The freshman class brings a different kind of energy. The published recruiting artifact contains 24 additions, led by five-star edge Carter Meadows and five-star running back Savion Hiter. Four-star linemen Titan Davis, Malakai Lee, Alister Vallejo and Marky Walbridge deepen the line-of-scrimmage bet. Hiter is the immediate fascination because he joins Jordan Marshall, a returning captain who ran for 932 yards and 10 touchdowns. Marshall supplies proof; Hiter supplies a change of pace and five-star upside. Together with Underwood’s legs, they can force a defense to solve several versions of the same run look.",
      "Everything still bends toward Bryce Underwood. He threw for 2,428 yards, ran for 392 more and started all 13 games as a true freshman. Those repetitions are valuable only if his offseason converted experience into command: faster pressure recognition, more consistent footwork, better timing with Andrew Marsh and fewer possessions rescued only by improvisation. Jason Beck’s task is to give Underwood defined answers without shrinking the offense. If the sophomore’s offseason was productive, Michigan’s 18th-ranked down-to-down efficiency finally has a chance to become points.",
      "The schedule will reveal the answer quickly. Western Michigan opens the season, but Oklahoma arrives in Week 2. Iowa follows two weeks later, and an October home stretch brings Penn State and Indiana before the rivalry game with Michigan State. November is the examination: a trip to Oregon, UCLA at home and Michigan at Ohio State. The favorable part is location—Oklahoma, Iowa, Penn State, Indiana, Michigan State and UCLA all come to Ann Arbor. The unforgiving part is that there are few places to hide if the offense remains unfinished.",
      "Whittingham’s best teams have made opponents carry the burden of playing clean football for four quarters. Michigan already owns pieces for that identity. Its 2025 defense ranked fourth nationally in yards allowed per successful opponent play and 20th in explosive-play rate allowed. Even when opponents won a snap, Michigan usually kept the win from becoming catastrophic. Add Daley’s pressure production and Hill’s organization, and the defense has a plausible path to giving the young offense time to mature rather than demanding a shootout every week.",
      "That is why Michigan belongs in the surprise-team conversation, with emphasis on surprise rather than certainty. The Wolverines are not importing Utah’s results; they are combining Utah’s demonstrated situational strength with a Michigan roster that already showed it could win ordinary downs. The upside appears if Whittingham’s standards take hold quickly, the transfers stabilize the transition, the freshmen add real competition and Underwood turns a full offseason into second-year control. Last year’s team often did enough to create an opportunity. This one may finally be built to finish it."
    ],sources:[{label:"ESPN reporting and Michigan's dismissal statement",url:"https://www.espn.com/college-football/story/_/id/47277170/fired-michigan-coach-sherrone-moore-custody-no-decision-charges"},{label:"Michigan names Kyle Whittingham head coach",url:"https://mgoblue.com/news/2025/12/27/kyle-whittingham-named-michigans-j-ira-and-nicki-harris-family-head-football-coach"},{label:"Michigan incoming transfers",url:"https://mgoblue.com/news/2026/1/7/incoming-transfers-to-michigan-football"},{label:"Michigan announces 2026 football schedule",url:"https://mgoblue.com/news/2026/1/27/michigan-announces-2026-football-schedule"},{label:"Michigan 2025 season review",url:"https://mgoblue.com/news/2026/1/7/season-review-2025-michigan-football"}]},
    {slug:"underwood-marsh-sophomore-connection",eyebrow:"OFFENSE · FILM ROOM",title:"Michigan’s offense can grow up fast if Bryce Underwood and Andrew Marsh grow together",deck:"The freshman records were the introduction. The sophomore challenge is turning one explosive connection into an offense that works every week.",published:"August 19, 2026",readMinutes:7,playerIds:["5141741","5141572"],coverQuestion:"Can one connection unlock the entire offense?",coverLabel:"QB × WR",coverTheme:"connection",tags:[tag("POSITION","qb","QB"),tag("POSITION","wr","WR"),tag("UNIT","offense","Offense"),tag("TOPIC","player-development","Player development"),tag("TOPIC","passing-game","Passing game")],dataLinks:[{label:"Bryce Underwood profile",href:"/players/5141741",description:"Review his 2025 passing and rushing production, usage grade and sophomore outlook."},{label:"Andrew Marsh profile",href:"/players/5141572",description:"See the receiving production behind Michigan's freshman record-setter."},{label:"Michigan offense",href:"/analytics/offense",description:"Track whether the passing game becomes more efficient under the new staff."}],body:[
      "The most important relationship in Michigan's 2026 offense already has a season of evidence behind it. Bryce Underwood threw for 2,428 yards as a true freshman. Andrew Marsh caught 45 passes for 651 yards and four touchdowns. Those are not projections or recruiting promises; they are the starting point for two sophomores who learned the speed of Big Ten football together.",
      "Their signature afternoon came at Wrigley Field, where Marsh caught 12 passes for 189 yards against Northwestern and established Michigan freshman single-game records in both categories. That game matters beyond the record book. It showed that when Michigan had to feed one matchup repeatedly, Underwood could locate it and Marsh could carry the volume.",
      "The next step is harder than the first. Defenses now have a full season of routes, tendencies and pressure responses to study. Underwood will see coverages designed to make him hold the ball. Marsh will see corners play with more help and more physical leverage. Improvement will show up less in one spectacular Saturday than in the routine answers: an efficient throw against pressure, a conversion on third-and-six, a route adjustment both players see the same way.",
      "Jason Beck's arrival changes the structure around them. Michigan has publicly described Beck as a creative quarterback developer who wants an efficient, balanced attack. That should create opportunities for defined reads off the run game, but the system cannot manufacture chemistry. Underwood and Marsh still have to own the timing.",
      "There is a useful tension here. Underwood's legs are a real weapon—392 rushing yards and six scores in 2025—but every scramble cannot become the offense's emergency plan. Marsh's job is to become the dependable answer before the pocket breaks down. Underwood's job is to trust that answer without forcing it.",
      "Michigan does not need them to become a finished NFL-style pairing by September. It needs their second season to look like a second season: fewer empty possessions, more control of obvious passing downs and enough explosive completions to stop opponents from crowding the backfield. If that happens, the offense's ceiling changes before any other position battle is settled."
    ],sources:[{label:"Michigan 2025 season review",url:"https://mgoblue.com/news/2026/1/7/season-review-2025-michigan-football"},{label:"Andrew Marsh and Micah Simon interview",url:"https://mgoblue.com/news/2026/6/10/mgoblue-podcasts-in-the-trenches-590-andrew-marsh-micah-simon-transcript"},{label:"2026 spring captains and leadership council",url:"https://mgoblue.com/news/2026/2/2/football-whittingham-announces-spring-captains-leadership-council"}]},
    {slug:"marshall-hiter-backfield",eyebrow:"RUN GAME · POSITION ROOM",title:"Jordan Marshall sets the floor. Savion Hiter could change the ceiling.",deck:"Michigan’s backfield pairs a proven 932-yard captain with the most decorated freshman runner in the class. Their value is in how differently they can stress a defense.",published:"August 19, 2026",readMinutes:7,playerIds:["5079574","5159046"],tags:[tag("POSITION","rb","RB"),tag("UNIT","offense","Offense"),tag("TOPIC","run-game","Run game"),tag("TOPIC","depth-chart","Depth chart")],dataLinks:[{label:"Jordan Marshall profile",href:"/players/5079574",description:"Explore his 2024-25 growth, verified production grade and projected RB1 role."},{label:"Savion Hiter profile",href:"/players/5159046",description:"See the five-star recruiting benchmark without treating it as college production."},{label:"Running back room",href:"/team/positions/rb",description:"Compare the full collection of backs around Marshall and Hiter."}],body:[
      "Jordan Marshall enters 2026 with something no recruiting ranking can replace: proof. He carried 150 times for 932 yards and 10 touchdowns last season, added 92 receiving yards and finished the year as Michigan's co-Offensive Player of the Year. In his five career starts, Michigan credits him with 124.2 rushing yards per game.",
      "That production makes him the room's floor. Marshall can handle the first carry, the fourth-quarter carry and the protection assignment between them. His 2025 workload placed him around the 90th percentile nationally among FBS running backs in SOAR's usage comparison. He is not simply the familiar name; he is the verified feature option.",
      "Savion Hiter enters from the opposite direction. His five-star composite and high-school résumé—1,445 rushing yards and 25 touchdowns as a senior after 1,698 and 26 as a junior—describe rare pedigree. They do not prove he is ready for Big Ten pass protection or a 20-carry afternoon. That distinction is why his profile shows a recruiting benchmark rather than a production grade.",
      "The interesting question is not whether Hiter immediately takes Marshall's job. It is whether the freshman gives Michigan a second style that changes what a defense must prepare for. Michigan's own offseason discussion has framed Marshall as the bruising presence and Hiter as a different kind of runner, with Bryson Kuzdzal offering another change of pace.",
      "That variety matters in Jason Beck's offense. A credible quarterback run threat already forces an extra defender to account for Underwood. A backfield that can shift from Marshall's contact balance to Hiter's acceleration can make the same formation produce a different problem. The benefit is not merely fresher legs; it is uncertainty for linebackers.",
      "The honest preseason hierarchy remains simple: Marshall is the accomplished captain and projected RB1. Hiter is the exceptional prospect who must earn college trust. If Michigan lets both truths coexist, the room can be exciting without becoming a manufactured controversy—and deep enough to carry the offense when November asks for difficult yards."
    ],sources:[{label:"Michigan 2025 season review",url:"https://mgoblue.com/news/2026/1/7/season-review-2025-michigan-football"},{label:"Michigan running backs discussion",url:"https://mgoblue.com/news/2026/6/24/mgoblue-podcasts-in-the-trenches-592-ron-bellamy-fred-jackson-transcript"},{label:"Savion Hiter official profile",url:"https://mgoblue.com/sports/football/roster/savion-hiter/28100"},{label:"2026 spring game participation",url:"https://mgoblue.com/news/2026/4/18/football-player-participation-maize-7-blue-6"}]},
    {slug:"john-henry-daley-pressure",eyebrow:"DEFENSE · TRANSFER IMPACT",title:"John Henry Daley is more than a transfer. He is the pressure plan walking through the door.",deck:"Michigan imported one of the nation’s most productive edge defenders—and a player who already understands the standards surrounding its new staff.",published:"August 19, 2026",readMinutes:6,playerIds:["5160962","4923036","5156353","4870704"],tags:[tag("POSITION","de","DE"),tag("POSITION","dt","DT"),tag("UNIT","defense","Defense"),tag("TOPIC","transfer-portal","Transfer portal"),tag("TOPIC","pass-rush","Pass rush")],dataLinks:[{label:"John Henry Daley profile",href:"/players/5160962",description:"See his Utah production, national usage context and projected role."},{label:"Michigan defense",href:"/analytics/defense",description:"Follow the front's pressure and explosive-play prevention once games begin."},{label:"Defensive end room",href:"/team/positions/de",description:"View the edge rotation surrounding Daley."}],body:[
      "Transfer additions are often introduced through possibility. John Henry Daley arrives with production too loud to hide behind that word. In 11 starts for Utah in 2025, he recorded 45 tackles, 17.5 tackles for loss and 11.5 sacks. Michigan's official transfer release noted that his tackle-for-loss total was tied for first nationally and his sack total tied for second through those 11 games.",
      "SOAR grades that season in the 98.7th percentile of the national FBS front-seven cohort. The exact grade is descriptive, not predictive, but it captures why Daley matters: Michigan is not asking an unknown player to discover disruption. It is asking a proven disruptor to bring it into a different conference and a deeper rotation.",
      "The fit is unusually clean. Daley played at Utah, the program Kyle Whittingham built, and now enters a Michigan defense coordinated by Jay Hill. He understands the physical expectations and the value of coordinated pressure. That familiarity should shorten the cultural translation even while the football translation remains real.",
      "Daley also changes the math for everybody inside him. Trey Pierce and Enow Etta do not need gaudy sack totals to affect the quarterback. If they compress the pocket and remove the easy step-up lane, an edge player with Daley's closing production gets cleaner finishes. Cameron Brandt and the rest of the edge room can attack a rotation rather than carry every obvious passing down.",
      "There is one sensible preseason caution: availability and adaptation still matter. Michigan's spring coverage noted that Daley was not on the field during spring work, so the fall integration deserves attention rather than assumption. A previous stat line cannot take a September snap.",
      "But the blueprint is clear. Michigan wants the interior to move the quarterback off his spot and the edges to make that movement expensive. Daley arrives as the most convincing evidence that the second half of that plan can work immediately."
    ],sources:[{label:"Michigan incoming transfers",url:"https://mgoblue.com/news/2026/1/7/incoming-transfers-to-michigan-football"},{label:"Michigan preseason honors",url:"https://mgoblue.com/news/2026/5/26/2026-michigan-football-preseason-honors"},{label:"Michigan defensive front discussion",url:"https://mgoblue.com/news/2026/5/6/mgoblue-podcasts-in-the-trenches-585-blake-frazier-transcript"}]},
    {slug:"team-147-leadership-spine",eyebrow:"TEAM 147 · LEADERSHIP",title:"The most important 2026 depth chart might be the one Michigan’s players voted for",deck:"Underwood, Marshall, Rod Moore and Trey Pierce form a spring captaincy group that connects youth, production and endurance.",published:"August 19, 2026",readMinutes:6,playerIds:["5141741","5079574","4603101","5156353"],tags:[tag("UNIT","offense","Offense"),tag("UNIT","defense","Defense"),tag("TOPIC","leadership","Leadership"),tag("TOPIC","team-identity","Team identity")],dataLinks:[{label:"Michigan importance board",href:"/team",description:"See the projected roles and evidence behind the players most tied to Michigan's ceiling."},{label:"Bryce Underwood profile",href:"/players/5141741",description:"The sophomore quarterback sits first on the preseason importance board."},{label:"Jordan Marshall profile",href:"/players/5079574",description:"The returning RB1 combines production with a player-voted leadership role."}],body:[
      "Depth charts tell us who is expected to take the first snap. Player votes tell us who the locker room expects to set the standard before that snap ever arrives. Michigan's spring captain group—Bryce Underwood, Jordan Marshall, Rod Moore and Trey Pierce—is therefore one of the most revealing pieces of the 2026 preseason.",
      "The offensive choices are striking because of their age. Underwood is a sophomore and Marshall a junior, yet teammates placed the new offense in their hands. That vote aligns with production: Underwood started all 13 games as a freshman, while Marshall surged to 932 rushing yards and 10 touchdowns. Leadership did not arrive instead of responsibility; it followed it.",
      "The defensive choices carry a different kind of weight. Moore's Michigan career has included high-level play and a long recovery path. Pierce enters the season at the center of a rebuilt defensive front. Together they give the defense voices rooted in persistence and line-of-scrimmage accountability.",
      "The composition matters for Kyle Whittingham's first Michigan team. A new coach can define standards, but the roster decides whether those standards travel into position meetings and difficult practices. Two captains from the young offensive core and two from the defensive spine create a useful bridge between a new staff and a roster with its own memory.",
      "Spring captaincy is not a permanent 2026 award; Michigan has said the team will vote again during fall camp. That makes this less a ceremonial conclusion than an early signal. Roles can evolve. Other leaders can emerge. The first vote still tells us where trust existed when the new era began.",
      "Michigan's playoff path will eventually be discussed through quarterback efficiency, rushing production and defensive stops. Before those numbers arrive, the captain vote supplies a human framework: the players most responsible for the season are already being asked to own it."
    ],sources:[{label:"Michigan announces spring captains and leadership council",url:"https://mgoblue.com/news/2026/2/2/football-whittingham-announces-spring-captains-leadership-council"},{label:"Michigan 2025 season review",url:"https://mgoblue.com/news/2026/1/7/season-review-2025-michigan-football"}]}
  ];
  return [...researched,{
    slug:"2026-coaching-staff", eyebrow:"THE NEW STAFF · 2026", title:"What Michigan's new coaching staff is built to do", deck:"Kyle Whittingham brings an experienced, physical program to Ann Arbor. Jason Beck and Jay Hill give it a clear football plan on both sides.", published:"August 18, 2026", readMinutes:7,
    tags:[tag("UNIT","offense","Offense"),tag("UNIT","defense","Defense"),tag("TOPIC","coaching","Coaching"),tag("TOPIC","scheme","Scheme")],
    dataLinks:[{label:"Michigan vs. Utah",href:"/analytics",description:"Compare the verified 2025 tendencies behind the coaching transition."},{label:"Coaching dashboard",href:"/analytics/coaching",description:"Follow Michigan's 2026 staff and observed play-calling identity."}],
    body:[
      "Michigan did not hire Kyle Whittingham to reinvent what winning football looks like in Ann Arbor. It hired a coach whose Utah teams were known for being hard to move, strong up front and comfortable winning games that required patience. Whittingham arrived after 21 seasons as Utah's head coach, a 177–88 record, three conference championships and eight seasons with at least 10 wins.",
      "The first thing Michigan fans should expect is a connected staff. Offensive coordinator Jason Beck worked under Whittingham at Utah in 2025, while defensive coordinator Jay Hill previously spent 12 years on Whittingham's Utah staff before leading Weber State and coordinating BYU's defense. This is not a collection of unfamiliar coaches learning one another on the fly. The head coach and both coordinators already share a working football language.",
      "Beck's offense is the most interesting change. His recent teams have paired quarterback development with a real running game instead of treating balance as a slogan. New Mexico ranked fourth nationally in total offense and fifth in rushing offense in 2024. At Michigan, Beck also coaches quarterbacks, Jim Harding handles the offensive line, Micah Simon coaches receivers and Freddie Whittingham works with tight ends. Tony Alford staying as run-game coordinator and running backs coach gives the room valuable Michigan continuity.",
      "The likely offensive identity is straightforward: make the quarterback comfortable, create movement in the run game and force defenses to defend the whole field. That does not guarantee instant production. It does give Michigan a sensible structure for developing a young offense without asking one player to carry every Saturday.",
      "Hill's defense should look just as familiar to Big Ten fans: physical, organized and difficult to score against. His BYU defenses finished among the nation's top 21 in scoring defense in both 2024 and 2025. Lewis Powell brings more than a decade of Utah defensive-line experience to the edge group, while Jernaro Gilford arrives after 10 seasons coaching BYU's cornerbacks.",
      "Special teams should remain a real part of the plan. Kerry Coombs stayed as coordinator, with Garrett Clawson continuing on staff. That continuity matters because Whittingham has never treated kicking and coverage units like an afterthought. Hill also spent nine seasons coordinating special teams at Utah.",
      "The honest preseason read is that Michigan has a coherent staff, not a finished product. Whittingham supplies the program standard. Beck must turn the offensive pieces into dependable points. Hill must make the defense play fast without losing discipline. If those three parts connect, Michigan should look like Michigan: strong at the line of scrimmage, prepared for close games and difficult to beat late in the season."
    ],
    sources:[
      {label:"Michigan names Kyle Whittingham head coach",url:"https://mgoblue.com/news/2025/12/27/kyle-whittingham-named-michigans-j-ira-and-nicki-harris-family-head-football-coach"},
      {label:"Michigan announces offensive staff",url:"https://mgoblue.com/news/2026/1/7/football-whittingham-announces-offensive-coaching-staff"},
      {label:"Jason Beck named offensive coordinator",url:"https://mgoblue.com/news/2026/1/2/football-jason-beck-named-michigans-sanford-robertson-offensive-coordinator"},
      {label:"Jay Hill named defensive coordinator",url:"https://mgoblue.com/news/2026/1/2/football-jay-hill-named-u-ms-lester-family-defensive-coordinator"},
      {label:"Michigan's 2026 coaching staff",url:"https://mgoblue.com/sports/football/coaches"}
    ]
  },{slug:"2026-class-blueprint",eyebrow:"RECRUITING · 2026",title:"Inside Michigan's 2026 class blueprint",deck:`${recruiting?.recruits.length ?? 0} commitments, one class identity, and the position map behind the national ranking.`,readMinutes:5,tags:[tag("UNIT","offense","Offense"),tag("UNIT","defense","Defense"),tag("TOPIC","recruiting","Recruiting"),tag("TOPIC","roster-building","Roster building")],dataLinks:[{label:"2026 recruiting class",href:"/recruiting",description:"Explore every published commitment, position and composite benchmark."},{label:"National recruiting board",href:"/recruiting/national",description:"Compare Michigan's class with the national field."}],body:[`Michigan's current 2026 class snapshot contains ${recruiting?.recruits.length ?? 0} commitments and sits No. ${recruiting?.ranking?.rank ?? "—"} nationally in the published source.`,"The star and composite columns describe recruiting consensus. The F–S+ display grade translates that composite without changing the underlying order.","The next layer is roster fit: where each player enters the position room, which future needs remain open, and how development changes the original recruiting expectation."]},...playerStories];
}

export function storyBySlug(slug:string){const aliases:Record<string,string>={"season-preview":"2026-coaching-staff","roster-watch":"2026-class-blueprint","history":"2026-coaching-staff"};return michiganStories().find(story=>story.slug===(aliases[slug]??slug))??null;}
export function storiesForPlayer(playerId:string){return michiganStories().filter(story=>story.playerIds?.includes(playerId));}

undefined
