import pytest
from cfb_analytics.analytics.opponent_adjusted_offense import calculate_opponent_adjusted_offense

def _row(*,game,team_id,team,opp_id,opp,points,possessions,successes,plays,scoring,points_allowed,possessions_allowed,successes_allowed,plays_allowed,scoring_allowed,yards=None,yards_allowed=None):
 yards=points*10 if yards is None else yards;yards_allowed=points_allowed*10 if yards_allowed is None else yards_allowed
 return {"season":2025,"classification":"fbs","opponent_classification":"fbs","gameValidationStatus":"PASS","gameId":game,"team_id":team_id,"team":team,"opponent_id":opp_id,"opponent":opp,"possessionPoints":points,"resolvedPointPossessions":possessions,"successfulPlays":successes,"successEligiblePlays":plays,"possessionTouchdowns":scoring,"possessionFieldGoals":0,"otherScoringPossessions":0,"validatedPossessions":possessions,"possessionYards":yards,"yardagePossessions":possessions,"possessionPointsAllowed":points_allowed,"resolvedPointPossessionsAllowed":possessions_allowed,"successfulPlaysAllowed":successes_allowed,"successEligiblePlaysAllowed":plays_allowed,"possessionTouchdownsAllowed":scoring_allowed,"possessionFieldGoalsAllowed":0,"otherScoringPossessionsAllowed":0,"validatedDefensivePossessions":possessions_allowed,"possessionYardsAllowed":yards_allowed,"yardagePossessionsAllowed":possessions_allowed}
def _sample_rows():
 return [_row(game="1",team_id=1,team="Alpha",opp_id=2,opp="Beta",points=35,possessions=10,successes=30,plays=60,scoring=5,points_allowed=14,possessions_allowed=10,successes_allowed=20,plays_allowed=60,scoring_allowed=2),_row(game="1",team_id=2,team="Beta",opp_id=1,opp="Alpha",points=14,possessions=10,successes=20,plays=60,scoring=2,points_allowed=35,possessions_allowed=10,successes_allowed=30,plays_allowed=60,scoring_allowed=5),_row(game="2",team_id=1,team="Alpha",opp_id=3,opp="Gamma",points=32,possessions=10,successes=29,plays=60,scoring=5,points_allowed=10,possessions_allowed=10,successes_allowed=18,plays_allowed=60,scoring_allowed=1),_row(game="2",team_id=3,team="Gamma",opp_id=1,opp="Alpha",points=10,possessions=10,successes=18,plays=60,scoring=1,points_allowed=32,possessions_allowed=10,successes_allowed=29,plays_allowed=60,scoring_allowed=5),_row(game="3",team_id=2,team="Beta",opp_id=3,opp="Gamma",points=21,possessions=10,successes=24,plays=60,scoring=3,points_allowed=17,possessions_allowed=10,successes_allowed=21,plays_allowed=60,scoring_allowed=2),_row(game="3",team_id=3,team="Gamma",opp_id=2,opp="Beta",points=17,possessions=10,successes=21,plays=60,scoring=2,points_allowed=21,possessions_allowed=10,successes_allowed=24,plays_allowed=60,scoring_allowed=3),_row(game="4",team_id=1,team="Alpha",opp_id=2,opp="Beta",points=38,possessions=10,successes=32,plays=60,scoring=6,points_allowed=17,possessions_allowed=10,successes_allowed=21,plays_allowed=60,scoring_allowed=2),_row(game="4",team_id=2,team="Beta",opp_id=1,opp="Alpha",points=17,possessions=10,successes=21,plays=60,scoring=2,points_allowed=38,possessions_allowed=10,successes_allowed=32,plays_allowed=60,scoring_allowed=6),_row(game="5",team_id=1,team="Alpha",opp_id=3,opp="Gamma",points=35,possessions=10,successes=31,plays=60,scoring=5,points_allowed=13,possessions_allowed=10,successes_allowed=19,plays_allowed=60,scoring_allowed=2),_row(game="5",team_id=3,team="Gamma",opp_id=1,opp="Alpha",points=13,possessions=10,successes=19,plays=60,scoring=2,points_allowed=35,possessions_allowed=10,successes_allowed=31,plays_allowed=60,scoring_allowed=5),_row(game="6",team_id=2,team="Beta",opp_id=3,opp="Gamma",points=24,possessions=10,successes=25,plays=60,scoring=3,points_allowed=20,possessions_allowed=10,successes_allowed=22,plays_allowed=60,scoring_allowed=3),_row(game="6",team_id=3,team="Gamma",opp_id=2,opp="Beta",points=20,possessions=10,successes=22,plays=60,scoring=3,points_allowed=24,possessions_allowed=10,successes_allowed=25,plays_allowed=60,scoring_allowed=3)]
def test_ranks_clear_best_offense_first():
 r=calculate_opponent_adjusted_offense(_sample_rows(),2025);assert [x["team"] for x in r]==["Alpha","Beta","Gamma"];assert r[0]["adjusted_yards_per_drive"]>r[1]["adjusted_yards_per_drive"]
def test_raw_and_deltas():
 a=next(x for x in calculate_opponent_adjusted_offense(_sample_rows(),2025) if x["team"]=="Alpha");assert a["raw_points_per_drive"]==pytest.approx(3.5);assert a["raw_success_rate"]==pytest.approx(122/240);assert a["raw_scoring_drive_rate"]==pytest.approx(21/40);assert a["raw_yards_per_drive"]==pytest.approx(35.0)
 for adj,raw,delta in (("adjusted_points_per_drive","raw_points_per_drive","points_per_drive_adjustment"),("adjusted_success_rate","raw_success_rate","success_rate_adjustment"),("adjusted_scoring_drive_rate","raw_scoring_drive_rate","scoring_drive_rate_adjustment"),("adjusted_yards_per_drive","raw_yards_per_drive","yards_per_drive_adjustment")):assert a[delta]==pytest.approx(a[adj]-a[raw])
def test_adjustment_identity_matches_average_opponent_allowance():
 r=calculate_opponent_adjusted_offense(_sample_rows(),2025)
 rows=_sample_rows();national=(sum(x["possessionPoints"] for x in rows)/sum(x["resolvedPointPossessions"] for x in rows),sum(x["possessionYards"] for x in rows)/sum(x["yardagePossessions"] for x in rows),sum(x["successfulPlays"] for x in rows)/sum(x["successEligiblePlays"] for x in rows),sum(x["possessionTouchdowns"] for x in rows)/sum(x["validatedPossessions"] for x in rows))
 for x in r:
  assert x["points_per_drive_adjustment"]==pytest.approx(national[0]-x["average_opponent_ppd_allowed_loo"]);assert x["yards_per_drive_adjustment"]==pytest.approx(national[1]-x["average_opponent_ypd_allowed_loo"]);assert x["success_rate_adjustment"]==pytest.approx(national[2]-x["average_opponent_success_rate_allowed_loo"]);assert x["scoring_drive_rate_adjustment"]==pytest.approx(national[3]-x["average_opponent_scoring_drive_rate_allowed_loo"])
def test_leave_one_out_really_excludes_graded_game():
 r=calculate_opponent_adjusted_offense(_sample_rows(),2025);a=next(x for x in r if x["team"]=="Alpha")
 # Beta defense allowed 110 points over four 10-drive games. Against Alpha in game 1 it allowed 35, so the LOO baseline is 75/30=2.50; against Alpha in game 4 it is 72/30=2.40. Gamma allowed 112 total, giving 80/30=2.6667 and 77/30=2.5667 when Alpha's games 2 and 5 are respectively removed. Equal Alpha drive counts make the schedule average 2.53333.
 expected=((110-35)/30+(110-38)/30+(112-32)/30+(112-35)/30)/4
 assert a["average_opponent_ppd_allowed_loo"]==pytest.approx(expected)
 assert a["average_opponent_ppd_allowed_loo"]==pytest.approx(2.533333333333333)
def test_yards_uses_yardage_possessions():
 rows=_sample_rows()
 for x in rows:
  if x["team"]=="Alpha":x["yardagePossessions"]*=2
 a=next(x for x in calculate_opponent_adjusted_offense(rows,2025) if x["team"]=="Alpha");assert a["raw_yards_per_drive"]==pytest.approx(17.5)
def test_filters_and_missing_field():
 rows=_sample_rows();junk=dict(rows[0]);junk.update({"gameId":"junk","team_id":99,"team":"Junk","classification":"fcs"});failed=dict(rows[0]);failed.update({"gameId":"failed","team_id":98,"team":"Failed","gameValidationStatus":"FAIL"});names={x["team"] for x in calculate_opponent_adjusted_offense(rows+[junk,failed],2025)};assert "Junk" not in names and "Failed" not in names
 del rows[0]["possessionYards"]
 with pytest.raises(ValueError,match="possessionYards"):calculate_opponent_adjusted_offense(rows,2025)
