import Link from "next/link";
import {currentRoster} from "../../lib/michigan/roster";
import {analyticsStory} from "../../lib/michigan/analytics";
import {homeData,opponentOf} from "../../lib/home-data";

const pct=(value:number)=>`${Math.round(value*100)}%`;

export default function TeamPage(){
  const roster=currentRoster();const importanceBoard=[...roster].sort((a,b)=>(a.importanceRank??999)-(b.importanceRank??999));const story=analyticsStory();const {schedule}=homeData();const returning=roster.filter(p=>p.rosterStatus==="RETURNING").length;const transfers=roster.filter(p=>p.rosterStatus==="TRANSFER").length;const freshmen=roster.filter(p=>p.rosterStatus==="FRESHMAN").length;const pressureGames=schedule.filter(game=>["Oklahoma","Penn State","Indiana","Oregon","Ohio State"].includes(opponentOf(game).name));
  return <div className="editorial-page"><section className="page-banner"><div className="wrap page-banner-inner"><div><span className="kicker">2026 MICHIGAN</span><h1>THE TEAM</h1><p>A player-by-player view of what returns, what the new Utah-connected staff inherits, and what must travel against a playoff-level schedule.</p><Link className="button primary" href="/team/depth-chart">PROJECTED LINEUP →</Link></div><div className="banner-mark">M</div></div><div className="wrap summary-rail"><span><small>ROSTER</small><b>{roster.length}</b></span><span><small>RETURNING</small><b>{returning}</b></span><span><small>TRANSFERS</small><b>{transfers}</b></span><span><small>FRESHMEN</small><b>{freshmen}</b></span></div></section>
  <div className="wrap editorial-stack">
    {story&&<section className="playoff-blueprint"><header className="section-header"><div><span className="kicker navy">THE PLAYOFF CASE</span><h2>Four things Michigan must make travel.</h2></div><small>PRESEASON ANALYSIS · NOT A FORECAST</small></header><div className="playoff-keys"><article><b>01</b><h3>Keep the rushing floor</h3><p>Michigan’s 2025 runs succeeded {pct(story.teams.michigan.rushSuccessRate)} of the time. That foundation must survive the staff change.</p></article><article><b>02</b><h3>Finish the field</h3><p>Michigan ranked No. {story.teams.michigan.pointsPerOpportunityNationalRank} in points per scoring opportunity. Utah finished No. {story.teams.utah.pointsPerOpportunityNationalRank} under this staff context.</p></article><article><b>03</b><h3>Win money downs</h3><p>Utah converted {pct(story.teams.utah.thirdDownConversionRate)} on third down. Michigan needs that kind of drive survival against the schedule’s best fronts.</p></article><article><b>04</b><h3>Keep explosives contained</h3><p>Michigan ranked No. {story.michiganDefense.yardsPerSuccessfulPlayAllowedNationalRank} in limiting the damage of successful opponent plays. That remains the defensive playoff trait.</p></article></div><p className="team-boundary">{story.interpretation.boundary}</p></section>}
    <section className="schedule-pressure"><div><span className="kicker maize">SCHEDULE PRESSURE</span><h2>The résumé will have enough opportunities.</h2><p>Oklahoma arrives in September. Penn State and defending champion Indiana come to Ann Arbor in October. The closing stretch includes Oregon in Eugene and Ohio State in Columbus. Michigan does not need perfection, but it cannot waste its home leverage or arrive in November without answers on the road.</p></div><div>{pressureGames.map(game=>{const opponent=opponentOf(game);return <span key={game.id}><small>WEEK {game.week} · {opponent.site}</small><b>{opponent.name}</b></span>})}</div></section>
    <section className="roster-analysis"><header className="section-header"><div><span className="kicker navy">PRESEASON IMPORTANCE</span><h2>Who matters most to Michigan’s ceiling?</h2></div><Link href="/team/depth-chart">DEPTH CHART →</Link></header><p className="roster-analysis-deck">Projected role comes first, then positional leverage and verified 2025 production. This is a sourced preseason importance ranking—not an official Michigan depth chart. Bryce Underwood is No. 1 because the starting quarterback has the greatest influence on the playoff path.</p><div className="importance-source"><span>PRESEASON IMPORTANCE · PROJECTED DEPTH UPDATED AUG. 8, 2026</span><a href="https://www.ourlads.com/ncaa-football/depth-charts/depth-chart/michigan/91119">SOURCE ↗</a></div><div className="team-player-list importance-list">{importanceBoard.map(player=>{const latest=player.insight?.pastSeasons[0];const freshman=player.rosterStatus==="FRESHMAN";return <Link href={`/players/${player.id}`} key={player.id}><b className="importance-rank">{String(player.importanceRank??"—").padStart(2,"0")}</b><div className="team-player-id">{player.playerImageUrl?<img src={player.playerImageUrl} alt=""/>:<b>{player.jersey??"M"}</b>}<span><small>#{player.jersey??"—"} · {player.position??"ATH"} · {player.importanceRole??"DEPTH"}</small><strong>{player.firstName} {player.lastName}</strong></span></div><div className="team-player-focus"><small>{freshman?"PROSPECT TIER":"PRODUCTION GRADE"} · {player.importanceTier}</small><strong>{freshman?(player.stars?`${player.stars}★`:"NR"):(player.performanceGrade??"NG")}</strong></div><div className="team-player-stats"><small>{latest?`${latest.season} · ${latest.team}`:"WHY HERE"}</small><span>{player.importanceReason}</span></div><p>{player.insight?.expectation}</p><em>→</em></Link>})}</div></section>
  </div></div>;
}
